[package]
name = "dep"
version = "0.1.0"
authors = ["hardliner66"]
edition = "2018"

[dependencies]
toml = "0.4.10"
serde = "1.0.87"
serde_derive = "1.0.87"
git2 = "0.7"
argparse = "0.2.2"
remove_dir_all = "0.5.1"
rpassword = "2.1.0"
whoami = "0.4.1"